### ISSUE TITLE
Command as console 

### ISSUE THREAD

**Issue by Felleus** [CyR1en/CommandPrompter#20] opened 2022-02-20 06:30 UTC
This issue/feature-request was posted in [Spigot](discussion link), but moved here so we can keep track of it.

# Content
```
Great plugin. Please make it possible to execute commands on behalf of the console, but at the same time the player could choose the necessary action, as is done now. Please
```

**Comment by CyR1en** [comment] 2022-02-20 07:15
Duplicate of #10

**Comment by CyR1en** [comment] 2022-07-13 19:32
Solved using permission attachments: https://github.com/CyR1en/CommandPrompter/commit/6edb950a86b2833c80565b9ce6eefa1a4e2279b6

**Closed by CyR1en** 2022-07-13 19:32 UTC
Labels: duplicate
